"""Simulation layer for formula-based EV charging simulation behavior."""

from simulation.comparison import (
    simulate_scenario_comparison,
    simulate_strategy_comparison,
)
from simulation.assignment import assign_chargers_fifo
from simulation.arrivals import generate_arrivals_count_by_timestep
from simulation.feeders import ModeledFeeder, expand_feeder_assets
from simulation.formulas import (
    calculate_available_site_capacity,
    calculate_daily_energy_demand,
    calculate_installed_charger_capacity,
    calculate_transformer_loading_percent,
    calculate_transformer_overload_kw,
    calculate_transformer_total_load,
)
from simulation.grid_loading import (
    calculate_feeder_allocation_shares,
    allocate_site_ev_load_to_feeders,
    build_feeder_loading_results,
    calculate_feeder_charger_shares,
)
from simulation.engine import (
    PlannerCandidateSimulationContext,
    build_planner_candidate_simulation_context,
    simulate,
    simulate_planner_candidate,
)
from simulation.load_profiles import (
    calculate_delivered_energy,
    calculate_unmet_energy,
    generate_smart_load_profile,
    generate_uncontrolled_load_profile,
)
from simulation.power_quality import (
    FeederPhaseAllocation,
    allocate_feeder_ev_load_to_phases,
    build_power_quality_result,
    build_feeder_phase_allocations,
    build_site_phase_load_series,
    calculate_current_imbalance_percent,
    calculate_harmonic_risk_score,
)
from simulation.requests import generate_charging_requests
from simulation.result import (
    ChargingRequestResult,
    FeederLoadingResult,
    FeederPowerQualityResult,
    GridLoadingResult,
    PlannerCandidateSimulationResult,
    PowerQualityResult,
    TransformerLoadingResult,
    charging_request_result_from_dict,
    charging_request_result_to_dict,
    feeder_loading_result_from_dict,
    feeder_loading_result_to_dict,
    feeder_power_quality_result_from_dict,
    feeder_power_quality_result_to_dict,
    grid_loading_result_from_dict,
    grid_loading_result_to_dict,
    SimulationResult,
    power_quality_result_from_dict,
    power_quality_result_to_dict,
    simulation_result_from_dict,
    simulation_result_to_dict,
    transformer_loading_result_from_dict,
    transformer_loading_result_to_dict,
)
from simulation.series import build_request_timestep_series
from simulation.time import (
    HOURS_PER_DAY,
    TIME_INDICES,
    TIMESTEP_HOURS,
    TIMESTEP_MINUTES,
    TIMESTEPS_PER_HOUR,
    TIMESTEPS_PER_DAY,
    calculate_charging_window_duration,
    calculate_time_window_duration_hours,
    calculate_time_window_duration_minutes,
    calculate_time_window_timestep_count,
    format_time_label,
    get_time_indices,
    get_time_labels,
    get_time_window_indices,
    get_timestep_hours,
    get_timestep_minutes,
    time_to_timestep_index,
    timestep_index_to_time,
)

__all__ = [
    "HOURS_PER_DAY",
    "ChargingRequestResult",
    "FeederLoadingResult",
    "FeederPowerQualityResult",
    "FeederPhaseAllocation",
    "GridLoadingResult",
    "ModeledFeeder",
    "PlannerCandidateSimulationResult",
    "PlannerCandidateSimulationContext",
    "PowerQualityResult",
    "SimulationResult",
    "TIME_INDICES",
    "TIMESTEP_HOURS",
    "TIMESTEP_MINUTES",
    "TIMESTEPS_PER_HOUR",
    "TIMESTEPS_PER_DAY",
    "TransformerLoadingResult",
    "assign_chargers_fifo",
    "calculate_charging_window_duration",
    "calculate_time_window_duration_hours",
    "calculate_time_window_duration_minutes",
    "calculate_time_window_timestep_count",
    "calculate_delivered_energy",
    "generate_arrivals_count_by_timestep",
    "build_request_timestep_series",
    "build_feeder_phase_allocations",
    "build_power_quality_result",
    "build_planner_candidate_simulation_context",
    "build_site_phase_load_series",
    "calculate_unmet_energy",
    "calculate_available_site_capacity",
    "calculate_current_imbalance_percent",
    "calculate_daily_energy_demand",
    "calculate_feeder_allocation_shares",
    "calculate_feeder_charger_shares",
    "calculate_installed_charger_capacity",
    "calculate_harmonic_risk_score",
    "calculate_transformer_loading_percent",
    "calculate_transformer_overload_kw",
    "calculate_transformer_total_load",
    "charging_request_result_from_dict",
    "charging_request_result_to_dict",
    "allocate_feeder_ev_load_to_phases",
    "feeder_loading_result_from_dict",
    "feeder_loading_result_to_dict",
    "feeder_power_quality_result_from_dict",
    "feeder_power_quality_result_to_dict",
    "expand_feeder_assets",
    "format_time_label",
    "generate_charging_requests",
    "generate_smart_load_profile",
    "generate_uncontrolled_load_profile",
    "get_time_indices",
    "get_time_labels",
    "get_time_window_indices",
    "get_timestep_hours",
    "get_timestep_minutes",
    "grid_loading_result_from_dict",
    "grid_loading_result_to_dict",
    "power_quality_result_from_dict",
    "power_quality_result_to_dict",
    "allocate_site_ev_load_to_feeders",
    "build_feeder_loading_results",
    "simulate",
    "simulate_planner_candidate",
    "simulate_scenario_comparison",
    "simulate_strategy_comparison",
    "simulation_result_from_dict",
    "simulation_result_to_dict",
    "time_to_timestep_index",
    "transformer_loading_result_from_dict",
    "transformer_loading_result_to_dict",
    "timestep_index_to_time",
]
